### ISSUE TITLE
New entry submission - PrivacyPros.io

### ISSUE THREAD

**Issue by bigbryan98** [btcpayserver/directory.btcpayserver.org#115]
New submission:

Name: PrivacyPros.io
Url: PrivacyPros.io
Type: merchants - cryptocurrency-paraphernalia
Description: PrivacyPros.io sells Billfodls, a seed phrase backup device and hardware wallets.  We also teach the world about how to maintain your digital privacy when using bitcoin and the internet in general.  We also provide cold storage consulting.

**Comment by Zaxounette** [comment]
Hi ! 

The directory is all about showcasing the different ways people use BTCPayServer.

Can you provide the actual URL where your instance is hosted, or a screen of the checkout if you use it for checkout ?
Or any other link for a BTCPayServer hosted app, crowdfund etc ...

Zaxounette.

**Comment by Zaxounette** [comment]
@bigbryan98 Still awaiting answer.

----
Will delete this issue after 20 days without an update.

**Comment by Zaxounette** [comment]
Closing for lack of reponse.

**Comment by bigbryan98** [comment]
Hey Zaxounette,

Im sorry this got buried somehow.

We are planning to implement the new shopify fix to our store when its
ready.  We were Billfodl.com (already on the merchant page) and have
switched/301ed everything to PrivacyPros.io

Our BTCPayServer is at btcpay.billfodl.com

We use it for invoicing as well as for donations at UnhashedPodcast.com

Does this answer your question?

Bryan

**Comment by Zaxounette** [comment]
@bigbryan98 Hi,
No problem for the buried mail/notifications !

All right now that's a lot of things to add in the directory :)

So for PrivacyPros.io, don't hesitate to open a new issue when you set up the shopify workaround/fix.

In the mean time, i'll add UnhashedPodcast.com to the directory, since it's not in there yet.
I'll also add btcpay.billfodl.com since you have registration open, unless told otherwise.

Zax.
