### ISSUE TITLE
New entry submission - The Break Club

### ISSUE THREAD

**Issue by GuidoBreaker** [btcpayserver/directory.btcpayserver.org#119]
New submission:

Name: The Break Club
Url: http://www.thebreakclub.com
Type: merchants - services
Description: Break Stuff Just For Fun!

![TheBreakClub_Rompiendo](https://user-images.githubusercontent.com/70299433/91368413-5e0f3680-e7df-11ea-9928-3ea9f5932e3b.jpg)

**Comment by Zaxounette** [comment]
Hi @GuidoBreaker !

The directory is all about showcasing the different ways people use BTCPayServer.

Can you provide the actual URL where your instance is hosted, or a screen of the checkout if you use it for checkout ?
Or any other link for a BTCPay Server hosted app, crowdfund etc ...

Doesn't need to be unique, just needs to actually use BTCPay Server in a way or another.

Thanks,
Zaxounette.

**Comment by Zaxounette** [comment]
FYI, will close after 20 days without an answer.

**Comment by GuidoBreaker** [comment]
Hi @Zaxounette! 
Its my first time here, so please be gentle! haha
I´m trying to upload this website to BTCPayServer and it asks for a GitHub account. I think I got the URL ok, (http://thebreakclub.com/) but please let me know how is it needed to be uploaded to do it properly. Thanks in advance!

**Comment by Zaxounette** [comment]
@GuidoBreaker 
No problem, you are in the right place to get your website into the BTCPay Server directory.

I just need to be sure that it uses BTCPay Server. 

That's why I asked you if you could give me the exact link to your BTCPay Server instance, a screenshot of the checkout process (if used for checkout), or any other link that can help me see that the website uses BTCPay Server.

I ask this because I can't see by myself anything relating to BTCPay Server on the website, or in the checkout payment options.

Thanks in advance,
Zax.

**Comment by Zaxounette** [comment]
Closing for lack of response.
